cmake_minimum_required(VERSION 3.30)
project(7777 C)

set(CMAKE_C_STANDARD 23)

add_executable(7777 План.c
	"Тестово поле.c"
	"Семинарни упражнения/Седмица - 3/Задача - 1.c"
        "Семинарни упражнения/Седмица - 3/Задача - 2.c"
        "Семинарни упражнения/Седмица - 3/Задача - 3.c"
        "Семинарни упражнения/Седмица - 3/Задача - 4.c"
        "Семинарни упражнения/Седмица - 3/Задача - 5.c"
        "Семинарни упражнения/Седмица - 3/Задача - 6.c"
        "Семинарни упражнения/Седмица - 3/Задача - 7.c"
        "Семинарни упражнения/Седмица - 3/Задача - 8.c"
        "Лабораторни упражнения/Седмица - 3/Задача - 1.c"
        "Лабораторни упражнения/Седмица - 3/Задача - 2.c"
        "Лабораторни упражнения/Седмица - 3/Задача - 3.c"
        "Лабораторни упражнения/Седмица - 3/Задача - 4.c"
	"Семинарни упражнения/Седмица - 3/Задача - 9.c"
	"Семинарни упражнения/Седмица - 3/Задача - 10.c"
        "Семинарни упражнения/Седмица - 3/Задача - 11.c"
        "Семинарни упражнения/Седмица - 3/Задача - 12.c"
        "Семинарни упражнения/Седмица - 3/Задача - 13.c"
        "Семинарни упражнения/Седмица - 3/Задача - 14.c"
        "Семинарни упражнения/Седмица - 3/Задача - 15.c"
        "Семинарни упражнения/Седмица - 3/Задача - 16.c"
	"Лабораторни упражнения/Седмица - 4/Задача - 1.c"
	"Лабораторни упражнения/Седмица - 4/Задача - 2.c"
	"Лабораторни упражнения/Седмица - 4/Задача - 3.c"
	"Лабораторни упражнения/Седмица - 4/Задача - 4.c"
	"Лабораторни упражнения/Седмица - 4/Задача - 5.c"
	"Лабораторни упражнения/Седмица - 4/Задача - 6.c"
	"Лабораторни упражнения/Седмица - 4/Задача - 7.c"
	"Семинарни упражнения/Седмица - 5/Задача - 2.c"
	"Семинарни упражнения/Седмица - 5/Задача - 4.c"
	"Семинарни упражнения/Седмица - 5/Задача - 6.c"
	"Семинарни упражнения/Седмица - 5/Задача - 8.c"
	"Семинарни упражнения/Седмица - 5/Задача - 12.c"
	"Лабораторни упражнения/Седмица - 5/Задача - 1.c"
	"Лабораторни упражнения/Седмица - 5/Задача - 2.c"
	"Лабораторни упражнения/Седмица - 5/Задача - 3.c"
	"Семинарни упражнения/Седмица - 5/Задача - 12(real).c"
	"Лабораторни упражнения/Седмица - 6/Задача - 1.c"
	"Лабораторни упражнения/Седмица - 6/Задача - 2.c"
	"Лабораторни упражнения/Седмица - 6/Задача - 3.c"
	"Семинарни упражнения/Седмица - 7/Задача - 1.c"
	"Семинарни упражнения/Седмица - 7/Задача - 2.c"
	"Семинарни упражнения/Седмица - 7/Задача - 3.c"
	"Семинарни упражнения/Седмица - 7/Задача - 4.c"
	"Семинарни упражнения/Седмица - 7/Задача - 5.c"
	"Семинарни упражнения/Седмица - 7/Задача - 6.c"
	"Семинарни упражнения/Седмица - 7/Задача - 7.c"
	"Семинарни упражнения/Седмица - 7/Задача - 8.c"
	"Семинарни упражнения/Седмица - 7/Задача - 9.c"
	"Лабораторни упражнения/Седмица - 7/Задача - 1.c"
	"Лабораторни упражнения/Седмица - 7/Задача - 2.c"
	"Лабораторни упражнения/Седмица - 7/Задача - 3.c"
	"Лабораторни упражнения/Седмица - 7/Задача - 4.c"
	"Семинарни упражнения/Седмица - 5/Задача - 1.c"
	"Семинарни упражнения/Седмица - 5/Задача - 3.c"
	"Семинарни упражнения/Седмица - 5/Задача - 5.c"
	"Семинарни упражнения/Седмица - 5/Задача - 7.c"
	"Семинарни упражнения/Седмица - 5/Задача - 9.c"
	"Семинарни упражнения/Седмица - 5/Задача - 10.c"
	"Семинарни упражнения/Седмица - 5/Задача - 11.c"
	"Лабораторни упражнения/Седмица - 8/Задача - 1.c"
	"Лабораторни упражнения/Седмица - 8/Задача - 2.c"
	"Лабораторни упражнения/Седмица - 8/Задача - 3.c"
	"Семинарни упражнения/Седмица - 9/Задача - 1.c"
	"Семинарни упражнения/Седмица - 9/Задача - 2.c"
	"Семинарни упражнения/Седмица - 9/Задача - 3.c"
	"Семинарни упражнения/Седмица - 9/Задача - 7.c"
	"Лабораторни упражнения/Седмица - 9/Задача - 1.c"
	"Лабораторни упражнения/Седмица - 9/Задача - 2.c"
	"Семинарни упражнения/Седмица - 9/Задача - 4.c"
	"Семинарни упражнения/Седмица - 9/Задача - 5.c"
	"Семинарни упражнения/Седмица - 9/Задача - 6.c"
	"Семинарни упражнения/Седмица - 9/Задача - 8.c"
	"Лабораторни упражнения/Седмица - 10/Задача - 1.c"
	"Лабораторни упражнения/Седмица - 10/Задача - 2.c"
	"Лабораторни упражнения/Седмица - 10/Задача - 3.c"
	"Семинарни упражнения/Седмица - 11/Задача - 1.c"
	"Семинарни упражнения/Седмица - 11/Задача - 2.c"
	"Семинарни упражнения/Седмица - 11/Задача - 5.c"
)
